# 我们开始吧~

In [1]:
import numpy as np

In [2]:
# 一维数组
x = np.array([1,2,3,4,5,6,7,8])

In [3]:
#二维数组
X = np.array(
    [
        [1,2,3,4],
        [5,6,7,8]
    ]
)

# 2

In [4]:
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
x

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
x.shape

(8,)

In [7]:
X.shape

(2, 4)

In [8]:
x.ndim

1

In [9]:
X.ndim

2

In [10]:
x.size

8

In [11]:
X.size


8

In [12]:
x.dtype

dtype('int32')

In [13]:
X.dtype

dtype('int32')

# 3.some 函数

### 使用arange创建数字序列

arange([start,]stop[,step,],dtype=None)

In [14]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

### 使用ones创建全是1的数组

np.ones(shape,dtype=None,order='C')
shape:2 or (2,3)

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

np.ones_like(a,dtype=None,order='C')

a 为一个array

In [18]:
np.ones_like(X)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.ones_like(x)

array([1, 1, 1, 1, 1, 1, 1, 1])

### 使用zeros创建全是0的数组

np.zeros()

np.zeros_like()

### 使用empty创建全是0的数组

数据是未初始化的，里面的值可能是随机值
empty(shape,dtype=float,order='C')

In [20]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [21]:
np.empty_like(X)

array([[4128860, 6029375, 3801155, 5570652],
       [6619251, 7536754,       0,       0]])

### 使用full创建指定值的数组 

np.full or np.full_like

In [22]:
np.full(10,66)

array([66, 66, 66, 66, 66, 66, 66, 66, 66, 66])

In [23]:
np.full((2,3),520)

array([[520, 520, 520],
       [520, 520, 520]])

In [24]:
np.full_like(X,1314)

array([[1314, 1314, 1314, 1314],
       [1314, 1314, 1314, 1314]])

### 使用random模块生成随机数的数组 

randn(d0,d1,...,dn)

In [25]:
np.random.randn()

-1.551461185802062

In [26]:
np.random.randn(3)

array([-0.21848937,  0.46594954, -0.66850543])

In [27]:
np.random.randn(2,3)

array([[ 0.80194229, -0.22983236,  0.79632865],
       [ 0.11365023,  0.55027274, -1.29862982]])

In [28]:
np.random.randn(5,1,2)

array([[[ 0.27822814, -1.19728627]],

       [[-0.23620879, -0.21266624]],

       [[-0.50917627,  1.16749922]],

       [[-1.91566019,  0.23133497]],

       [[-0.14423177,  0.83526353]]])

## array可进行大量数学函数计算一些函数 

In [29]:
A = np.arange(10).reshape(2,5)
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [30]:
A.shape

(2, 5)

In [31]:
A-1

array([[-1,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  8]])

In [32]:
A**2


array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [33]:
np.sin(A)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849]])

In [34]:
np.cos(A)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026]])